`timescale 1ns/1ps

// -------------------------------------------------------------------
// Testbench for golay_err_gen.sv (vector-driven)
//
// Reads the golden vectors generated by the Python model
// (model/golay_decoder.ipynb, section 2.2) and compares the DUT outputs
// against the expected ones, line by line.
//
// Vector file format (one vector per line, space separated):
//    1. i_syn           (12 bits)  s
//    2. i_q             (12 bits)  q
//    3. i_res_syn       (12 bits)  s ^ bi
//    4. i_res_q         (12 bits)  q ^ bi
//    5. i_w_syn         ( 4 bits)  w(s)
//    6. i_w_q           ( 4 bits)  w(q)
//    7. i_idx_syn       ( 4 bits)
//    8. i_idx_q         ( 4 bits)
//    9. i_found_syn     ( 1 bit )
//   10. i_found_q       ( 1 bit )
//   11. o_err           (24 bits)  expected error mask
//   12. o_uncorrectable ( 1 bit )  expected uncorrectable flag
//
// The file does not carry w(s^bi) / w(q^bi), so i_w_res_syn and
// i_w_res_q are computed here as the popcount of i_res_syn / i_res_q.
//
// The vector file can be overridden from the simulator command line, e.g.
//   iverilog: vvp sim +VECTOR_FILE=<path>
//   xsim    : -testplusarg VECTOR_FILE=<path>
// -------------------------------------------------------------------
module tb_golay_err_gen;

    localparam int NB_WORD = 12;
    localparam int NB_ERR  = 24;
    localparam int NB_CNT  =  4;

    localparam string DEFAULT_VECTOR_FILE =
        "/home/abel/Desktop/desktop/github_repos/fec-lab2/model/outputs/decoder/golay_err_gen_vectors.txt";

    // Max number of mismatches printed in detail
    localparam int MAX_PRINT = 20;

    // DUT inputs
    logic [NB_WORD - 1 : 0] i_syn;
    logic [NB_WORD - 1 : 0] i_q;
    logic [NB_WORD - 1 : 0] i_res_syn;
    logic [NB_WORD - 1 : 0] i_res_q;
    logic [NB_CNT  - 1 : 0] i_w_syn;
    logic [NB_CNT  - 1 : 0] i_w_q;
    logic [NB_CNT  - 1 : 0] i_idx_syn;
    logic [NB_CNT  - 1 : 0] i_idx_q;
    logic                   i_found_syn;
    logic                   i_found_q;
    logic [NB_CNT  - 1 : 0] i_w_res_syn;
    logic [NB_CNT  - 1 : 0] i_w_res_q;

    // DUT outputs
    logic [NB_ERR  - 1 : 0] o_err;
    logic                   o_uncorrectable;

    // Expected outputs (from file)
    logic [NB_ERR  - 1 : 0] exp_err;
    logic                   exp_uncorrectable;

    golay_err_gen #(
        .NB_WORD         (NB_WORD),
        .NB_ERR          (NB_ERR),
        .NB_CNT          (NB_CNT)
    ) dut (
        .i_syn           (i_syn),
        .i_q             (i_q),
        .i_res_syn       (i_res_syn),
        .i_res_q         (i_res_q),
        .i_w_syn         (i_w_syn),
        .i_w_q           (i_w_q),
        .i_idx_syn       (i_idx_syn),
        .i_idx_q         (i_idx_q),
        .i_found_syn     (i_found_syn),
        .i_found_q       (i_found_q),
        .o_err           (o_err),
        .o_uncorrectable (o_uncorrectable),
        .i_w_res_syn     (i_w_res_syn),
        .i_w_res_q       (i_w_res_q)
    );

    // w(s^bi) / w(q^bi): not present in the vector file
    assign i_w_res_syn = NB_CNT'($countones(i_res_syn));
    assign i_w_res_q   = NB_CNT'($countones(i_res_q));

    int    fd;
    int    n_read;
    int    line_num   = 0;
    int    n_vectors  = 0;
    int    err_fails  = 0;
    int    unc_fails  = 0;
    int    fails      = 0;
    string vector_file;

    initial begin
        $dumpfile("tb_golay_err_gen.vcd");
        $dumpvars(0, tb_golay_err_gen);

        if (!$value$plusargs("VECTOR_FILE=%s", vector_file))
            vector_file = DEFAULT_VECTOR_FILE;

        fd = $fopen(vector_file, "r");
        if (fd == 0) begin
            $display("[FATAL] Could not open vector file: %s", vector_file);
            $finish;
        end
        $display("[INFO] Reading vectors from %s", vector_file);

        while (!$feof(fd)) begin
            n_read = $fscanf(fd, "%b %b %b %b %b %b %b %b %b %b %b %b\n",
                             i_syn, i_q, i_res_syn, i_res_q,
                             i_w_syn, i_w_q, i_idx_syn, i_idx_q,
                             i_found_syn, i_found_q,
                             exp_err, exp_uncorrectable);
            line_num++;

            if (n_read != 12) begin
                if (n_read > 0)
                    $display("[WARN] line %0d: malformed vector (%0d fields), skipped",
                             line_num, n_read);
            end
            else begin
                #1;
                n_vectors++;

                if ((o_err !== exp_err) || (o_uncorrectable !== exp_uncorrectable)) begin
                    fails++;
                    if (o_err !== exp_err)                     err_fails++;
                    if (o_uncorrectable !== exp_uncorrectable) unc_fails++;

                    if (fails <= MAX_PRINT)
                        $display({"[FAIL] line %0d | s=%b q=%b rs=%b rq=%b ",
                                  "w_s=%0d w_q=%0d w_rs=%0d w_rq=%0d ",
                                  "idx_s=%0d idx_q=%0d f_s=%0b f_q=%0b\n",
                                  "        o_err DUT=%b exp=%b | o_unc DUT=%0b exp=%0b"},
                                 line_num, i_syn, i_q, i_res_syn, i_res_q,
                                 i_w_syn, i_w_q, i_w_res_syn, i_w_res_q,
                                 i_idx_syn, i_idx_q, i_found_syn, i_found_q,
                                 o_err, exp_err, o_uncorrectable, exp_uncorrectable);
                end

                #9;
            end
        end

        $fclose(fd);

        $display("--------------------------------------------------");
        $display(" golay_err_gen: %0d vectors, %0d failed", n_vectors, fails);
        $display("   o_err mismatches           : %0d", err_fails);
        $display("   o_uncorrectable mismatches : %0d", unc_fails);
        if (fails > MAX_PRINT)
            $display("   (only the first %0d failures were printed)", MAX_PRINT);
        if (n_vectors == 0)
            $display(" RESULT: NO VECTORS READ");
        else if (fails == 0)
            $display(" RESULT: PASS");
        else
            $display(" RESULT: FAIL");
        $display("--------------------------------------------------");
        $finish;
    end

endmodule
