`timescale 1ns/1ps

// -------------------------------------------------------------------
// Testbench for error_injection.sv (vector-driven)
//
// Reads the golden vectors generated by the Python model and compares
// the DUT output against the expected one, line by line.
//
// Vector file format (one vector per line, space separated):
//    1. i_codeword             (24 bits)  input codeword
//    2. i_error                (24 bits)  error pattern
//    3. o_codeword_with_errors (24 bits)  expected output (i_codeword ^ i_error)
//
// The vector file can be overridden from the simulator command line, e.g.
//   iverilog: vvp sim +VECTOR_FILE=<path>
//   xsim    : -testplusarg VECTOR_FILE=<path>
// -------------------------------------------------------------------
module tb_error_injection;

    localparam int NB_CODEWORD = 24;

    localparam string DEFAULT_VECTOR_FILE =
        "/home/abel/Desktop/desktop/github_repos/fec-lab2/implem/error_injection/error_injection_testing/all_errors_cw.txt";

    // Max number of mismatches printed in detail
    localparam int MAX_PRINT = 20;

    // DUT inputs
    logic [NB_CODEWORD - 1 : 0] i_codeword;
    logic [NB_CODEWORD - 1 : 0] i_error;

    // DUT output
    logic [NB_CODEWORD - 1 : 0] o_codeword_with_errors;

    // Expected output (from file)
    logic [NB_CODEWORD - 1 : 0] exp_codeword_with_errors;

    error_injection #(
        .NB_CODEWORD (NB_CODEWORD)
    ) dut (
        .i_codeword             (i_codeword),
        .i_error                (i_error),
        .o_codeword_with_errors (o_codeword_with_errors)
    );

    int    fd;
    int    n_read;
    int    line_num  = 0;
    int    n_vectors = 0;
    int    fails     = 0;
    string vector_file;

    initial begin
        $dumpfile("tb_error_injection.vcd");
        $dumpvars(0, tb_error_injection);

        if (!$value$plusargs("VECTOR_FILE=%s", vector_file))
            vector_file = DEFAULT_VECTOR_FILE;

        fd = $fopen(vector_file, "r");
        if (fd == 0) begin
            $display("[FATAL] Could not open vector file: %s", vector_file);
            $finish;
        end
        $display("[INFO] Reading vectors from %s", vector_file);

        while (!$feof(fd)) begin
            n_read = $fscanf(fd, "%b %b %b\n",
                             i_codeword, i_error, exp_codeword_with_errors);
            line_num++;

            if (n_read != 3) begin
                if (n_read > 0)
                    $display("[WARN] line %0d: malformed vector (%0d fields), skipped",
                             line_num, n_read);
            end
            else begin
                #1;
                n_vectors++;

                if (o_codeword_with_errors !== exp_codeword_with_errors) begin
                    fails++;
                    if (fails <= MAX_PRINT)
                        $display({"[FAIL] line %0d | cw=%b err=%b\n",
                                  "        o_codeword_with_errors DUT=%b exp=%b"},
                                 line_num, i_codeword, i_error,
                                 o_codeword_with_errors, exp_codeword_with_errors);
                end

                #9;
            end
        end

        $fclose(fd);

        $display("--------------------------------------------------");
        $display(" error_injection: %0d vectors, %0d failed", n_vectors, fails);
        if (fails > MAX_PRINT)
            $display("   (only the first %0d failures were printed)", MAX_PRINT);
        if (n_vectors == 0)
            $display(" RESULT: NO VECTORS READ");
        else if (fails == 0)
            $display(" RESULT: PASS");
        else
            $display(" RESULT: FAIL");
        $display("--------------------------------------------------");
        $finish;
    end

endmodule
