`timescale 1ns/1ps

// -------------------------------------------------------------------
// Testbench for golay_encoder.sv (vector-driven)
//
// Reads the golden vectors generated by the Python model and compares
// the DUT output against the expected one, line by line.
//
// Vector file format (one vector per line, space separated):
//    1. i_word (12 bits)  input message
//    2. cw     (24 bits)  expected codeword
//
// The vector file can be overridden from the simulator command line, e.g.
//   iverilog: vvp sim +VECTOR_FILE=<path>
//   xsim    : -testplusarg VECTOR_FILE=<path>
// -------------------------------------------------------------------
module tb_golay_encoder;

    localparam int NB_WORD     = 12;
    localparam int NB_CODEWORD = 24;

    localparam string DEFAULT_VECTOR_FILE =
        "/home/abel/Desktop/desktop/github_repos/fec-lab2/implem/golay_encoder/golay_encoder_testing/encoder_output.txt";

    // Max number of mismatches printed in detail
    localparam int MAX_PRINT = 20;

    // DUT input
    logic [NB_WORD     - 1 : 0] i_word;

    // DUT output
    logic [NB_CODEWORD - 1 : 0] cw;

    // Expected output (from file)
    logic [NB_CODEWORD - 1 : 0] exp_cw;

    golay_encoder #(
        .NB_WORD     (NB_WORD),
        .NB_CODEWORD (NB_CODEWORD)
    ) dut (
        .i_word (i_word),
        .cw     (cw)
    );

    int    fd;
    int    n_read;
    int    line_num  = 0;
    int    n_vectors = 0;
    int    fails     = 0;
    string vector_file;

    initial begin
        $dumpfile("tb_golay_encoder.vcd");
        $dumpvars(0, tb_golay_encoder);

        if (!$value$plusargs("VECTOR_FILE=%s", vector_file))
            vector_file = DEFAULT_VECTOR_FILE;

        fd = $fopen(vector_file, "r");
        if (fd == 0) begin
            $display("[FATAL] Could not open vector file: %s", vector_file);
            $finish;
        end
        $display("[INFO] Reading vectors from %s", vector_file);

        while (!$feof(fd)) begin
            n_read = $fscanf(fd, "%b %b\n", i_word, exp_cw);
            line_num++;

            if (n_read != 2) begin
                if (n_read > 0)
                    $display("[WARN] line %0d: malformed vector (%0d fields), skipped",
                             line_num, n_read);
            end
            else begin
                #1;
                n_vectors++;

                if (cw !== exp_cw) begin
                    fails++;
                    if (fails <= MAX_PRINT)
                        $display("[FAIL] line %0d | i_word=%b | cw DUT=%b exp=%b",
                                 line_num, i_word, cw, exp_cw);
                end

                #9;
            end
        end

        $fclose(fd);

        $display("--------------------------------------------------");
        $display(" golay_encoder: %0d vectors, %0d failed", n_vectors, fails);
        if (fails > MAX_PRINT)
            $display("   (only the first %0d failures were printed)", MAX_PRINT);
        if (n_vectors == 0)
            $display(" RESULT: NO VECTORS READ");
        else if (fails == 0)
            $display(" RESULT: PASS");
        else
            $display(" RESULT: FAIL");
        $display("--------------------------------------------------");
        $finish;
    end

endmodule
