`timescale 1ns/1ps

// -------------------------------------------------------------------
// Testbench for golay_correct.sv (vector-driven)
//
// Reads the golden vectors generated by the Python model and compares
// the DUT outputs against the expected ones, line by line.
//
// Vector file format (one vector per line, space separated):
//    1. i_rx        (24 bits)  received word
//    2. i_err       (24 bits)  error mask
//    3. o_cw        (24 bits)  expected corrected codeword (i_rx ^ i_err)
//    4. o_msg       (12 bits)  expected message (o_cw[23:12])
//    5. o_corrected ( 1 bit )  expected corrected flag (i_err != 0)
//
// The vector file can be overridden from the simulator command line, e.g.
//   iverilog: vvp sim +VECTOR_FILE=<path>
//   xsim    : -testplusarg VECTOR_FILE=<path>
// -------------------------------------------------------------------
module tb_golay_correct;

    localparam int NB_CW  = 24;
    localparam int NB_MSG = 12;

    localparam string DEFAULT_VECTOR_FILE =
        "/home/abel/Desktop/desktop/github_repos/fec-lab2/implem/golay_decoder/golay_correct/golay_correct_testing/golay_correct_vectors.txt";

    // Max number of mismatches printed in detail
    localparam int MAX_PRINT = 20;

    // DUT inputs
    logic [NB_CW  - 1 : 0] i_rx;
    logic [NB_CW  - 1 : 0] i_err;

    // DUT outputs
    logic [NB_CW  - 1 : 0] o_cw;
    logic [NB_MSG - 1 : 0] o_msg;
    logic                  o_corrected;

    // Expected outputs (from file)
    logic [NB_CW  - 1 : 0] exp_cw;
    logic [NB_MSG - 1 : 0] exp_msg;
    logic                  exp_corrected;

    golay_correct dut (
        .i_rx        (i_rx),
        .i_err       (i_err),
        .o_cw        (o_cw),
        .o_msg       (o_msg),
        .o_corrected (o_corrected)
    );

    int    fd;
    int    n_read;
    int    line_num   = 0;
    int    n_vectors  = 0;
    int    cw_fails   = 0;
    int    msg_fails  = 0;
    int    cor_fails  = 0;
    int    fails      = 0;
    string vector_file;

    initial begin
        $dumpfile("tb_golay_correct.vcd");
        $dumpvars(0, tb_golay_correct);

        if (!$value$plusargs("VECTOR_FILE=%s", vector_file))
            vector_file = DEFAULT_VECTOR_FILE;

        fd = $fopen(vector_file, "r");
        if (fd == 0) begin
            $display("[FATAL] Could not open vector file: %s", vector_file);
            $finish;
        end
        $display("[INFO] Reading vectors from %s", vector_file);

        while (!$feof(fd)) begin
            n_read = $fscanf(fd, "%b %b %b %b %b\n",
                             i_rx, i_err, exp_cw, exp_msg, exp_corrected);
            line_num++;

            if (n_read != 5) begin
                if (n_read > 0)
                    $display("[WARN] line %0d: malformed vector (%0d fields), skipped",
                             line_num, n_read);
            end
            else begin
                #1;
                n_vectors++;

                if ((o_cw        !== exp_cw)  ||
                    (o_msg       !== exp_msg) ||
                    (o_corrected !== exp_corrected)) begin
                    fails++;
                    if (o_cw        !== exp_cw)        cw_fails++;
                    if (o_msg       !== exp_msg)       msg_fails++;
                    if (o_corrected !== exp_corrected) cor_fails++;

                    if (fails <= MAX_PRINT)
                        $display({"[FAIL] line %0d | rx=%b err=%b\n",
                                  "        o_cw  DUT=%b exp=%b\n",
                                  "        o_msg DUT=%b exp=%b | o_corrected DUT=%0b exp=%0b"},
                                 line_num, i_rx, i_err,
                                 o_cw, exp_cw,
                                 o_msg, exp_msg, o_corrected, exp_corrected);
                end

                #9;
            end
        end

        $fclose(fd);

        $display("--------------------------------------------------");
        $display(" golay_correct: %0d vectors, %0d failed", n_vectors, fails);
        $display("   o_cw mismatches        : %0d", cw_fails);
        $display("   o_msg mismatches       : %0d", msg_fails);
        $display("   o_corrected mismatches : %0d", cor_fails);
        if (fails > MAX_PRINT)
            $display("   (only the first %0d failures were printed)", MAX_PRINT);
        if (n_vectors == 0)
            $display(" RESULT: NO VECTORS READ");
        else if (fails == 0)
            $display(" RESULT: PASS");
        else
            $display(" RESULT: FAIL");
        $display("--------------------------------------------------");
        $finish;
    end

endmodule
